### ISSUE TITLE
REQ-302 - 환경설정 기능 구현

### ISSUE THREAD

**Issue by jin123346** [greenlotte4/team3-lotteon-project#50]
환경설정 기능을 구현한다.
- 기본 설정
- 배너 관리
- 약관 관리
- 버전 관리

**Comment by KYW99** [comment]
기본 설정 작업 완료
버전 관리 페이징 작업 제외 완료

**Comment by jungmayo** [comment]
배너관리 -> 1차 개발 완료 (페이징작업제외, 이미지 각 배너위치에 띄우기 제외, 배경색, 이미지크기 제외)
